### ISSUE TITLE
kubernetes object for cluster

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/rancher-training#23]
cluster

```yaml
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: kube01
  namespace: fleet-default
spec:
  kubernetesVersion: v1.30.6+rke2r1
  rkeConfig:
    machinePools:
      - cloudCredentialSecretName: cattle-global-data:do-token
        controlPlaneRole: true
        displayName: ma
        etcdRole: true
        machineConfigRef:
          kind: DigitaloceanConfig
          name: ma
        name: ma
        quantity: 1
      - cloudCredentialSecretName: cattle-global-data:do-token
        displayName: wo
        machineConfigRef:
          kind: DigitaloceanConfig
          name: wo
        name: wo
        quantity: 2
        workerRole: true
```

ma

```yaml
apiVersion: rke-machine-config.cattle.io/v1
kind: DigitaloceanConfig
metadata:
  name: ma
  namespace: fleet-default
region: fra1
size: s-2vcpu-2gb
image: debian-12-x64
```

wo

```yaml
apiVersion: rke-machine-config.cattle.io/v1
kind: DigitaloceanConfig
metadata:
  name: wo
  namespace: fleet-default
region: fra1
size: s-2vcpu-4gb
image: debian-12-x64
```

sec

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: do-token
  namespace: cattle-global-data
type: Opaque
stringData:
  digitaloceancredentialConfig-accessToken: xxx
```
