### ISSUE TITLE
example of navlinks.ui.cattle.io

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/rancher-training#25]
- `navlinks.ui.cattle.io`
- https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/custom-branding

```yaml
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: grafana
spec:
  group: "Monitoring Dashboards"
  toURL: https://<RANCHER_SERVER_URL>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/?orgId=1
```
